version: "3.3"
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73_LAB1
    depends_on:
      - db
    volumes:
      - ./php:/var/html/
    ports:
      - "8080:80"
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
    ports:
      - "6033:3306"
